version: "3"
services:
  mongo:
    container_name: "mongo"
    image: mongo:3
  
  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  graylog:
    container_name: "graylog"
    image: graylog/graylog:3.3
    depends_on: 
      - mongo
      - elasticsearch
    links: 
      - mongo
      - elasticsearch
    expose: 
      - 9000
    ports: 
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
    environment: 
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/