apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
        ports:
        - containerPort: 80
        env:
          - name: "http.host"
            value: 0.0.0.0
          - name: "ES_JAVA_OPTS"
            value: "-Xms512m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: elasticsearch